### ISSUE TITLE
Ler livro sobre WebRTC: Web e WebRTC

### ISSUE THREAD

**Issue by marcelo-bn** [marcelo-osvaldo-smu/jogo-web-smu#2]
Sobre o livro [High Performance Browse Networking](https://hpbn.co/):

Essencial para a disciplina de SMU: capítulos 11, 12, 15, 17 e principalmente 18.
Depende de #1.

**Comment by osvaldosneto** [comment]
HTTP/1: é um protocolo de transporte que fornece conexão entre o cliente e o servidor geralmente depende de TCP.

HTTP/2: é um protocolo binário, feito para ser entendido por máquinas, não mais por pessoas. (As requisições e respostas são paralelas e assíncronas)

XMLHttpRequest: permite que as requisições HTTP sejam feitas via browser, permite a comunicação assííncrona com o servidor, através de script (JavaScript), sem que seja iniciada uma nova janela , não tendo a necessidade de atualização da página, sendo possível criar páginas mais interativas.

WebRTC: API que permite a troca de mensagens seja de audio, texto ou video em tempo real.
