### ISSUE TITLE
Conhecer frameworks de desenvolvimento de jogos Web

### ISSUE THREAD

**Issue by marcelo-bn** [marcelo-osvaldo-smu/jogo-web-smu#3]
Uma sugestão para o desenvolvimento do jogos Web é o uso de um framework para facilitar a interface e manipulação dos objetos. Dentre os vários disponíveis, o [Phaser](https://phaser.io/) se apresenta como uma boa opção.

Há o repositório [boidacarapreta/phaser3](https://github.com/boidacarapreta/phaser3) com o tutorial básico do framework convertido em commits e adaptado para uso de tela de toque. Além disso, estão também publicados os jogos criados pelas turmas do Integrado.

**Comment by osvaldosneto** [comment]
Optamos por não utilizar o Phaser, mas sim um jogo desenvolvido por nós.
Obs.: Caso o nosso jogo não seja aprovado pelo professor, podemos discutir novamente.

**Comment by ghost** [comment]
> Optamos por não utilizar o Phaser, mas sim um jogo desenvolvido por nós.
> Obs.: Caso o nosso jogo não seja aprovado pelo professor, podemos discutir novamente.

Desde que seja possível implementar comunicação por tempo real, está ótimo.
