### ISSUE TITLE
Ler RFC 3261: SIP

### ISSUE THREAD

**Issue by marcelo-bn** [marcelo-osvaldo-smu/jogo-web-smu#5]
Ler a [RFC 3261](https://datatracker.ietf.org/doc/html/rfc3261): seções 1, 2, 4, 5, 6, 7, 7.1 e 7.2.

**Comment by osvaldosneto** [comment]
- Overview of SIP Functionality
- Terminology
- Overview of Operation
- Structure of the Protocol
- Definitions
- SIP Messages
