### ISSUE TITLE
Implementar protocolo de sinalização v0.1 no cliente: registro 

### ISSUE THREAD

**Issue by marcelo-bn** [marcelo-osvaldo-smu/jogo-web-smu#9]
Implementar o protocolo em sua versão preliminar, v0.1, especificado na tarefa #7. No caso, apenas o registro do cliente no servidor - tarefa #9. Ainda não é necessário sala ou namespace para isolar os jogadores em partidas concorrentes.

**Comment by marcelo-bn** [comment]
link para o código: https://github.com/marcelo-osvaldo-smu/jogo-web-smu/blob/main/testes/socketIO/public/registro.js

**Comment by ghost** [comment]
> link para o código: https://github.com/marcelo-osvaldo-smu/jogo-web-smu/blob/main/testes/socketIO/public/registro.js

O link está quebrado. Melhor referenciar o _commit_ no comentário - ao invés da última versão do código.

**Comment by marcelo-bn** [comment]
Não consegui encontrar o commi exato, vou começar a adquirir essa prática daqui em diante.
Dessa forma, segue o link do [código](https://github.com/marcelo-osvaldo-smu/jogo-web-smu/blob/main/testes/socketIO/public/jogo.js) do cliente com a implementação.
